[versions]
# Library Versions
minecraft-version = "1.21.11"

fabric-loader = "0.18.4"
fabric-api = "0.141.2+1.21.11"
fabric-kotlin = "1.13.8+kotlin.2.3.0"

lwjgl = "3.3.3"
discord-ipc = "1.1"
reflections = "0.10.2"
httpclient = "4.5.14"
devauth = "1.2.2"

# Plugins Versions
kotlin = "2.3.0"
loom = "1.15-SNAPSHOT"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft-version" }

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }

nanovg = { group = "org.lwjgl", name = "lwjgl-nanovg", version.ref = "lwjgl" }
discord-ipc = { module = "meteordevelopment:discord-ipc", version.ref = "discord-ipc" }
reflections = { module = "org.reflections:reflections", version.ref = "reflections" }
httpclient = { module = "org.apache.httpcomponents:httpclient", version.ref = "httpclient" }
devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }

[bundles]
fabric = ["fabric-loader", "fabric-api", "fabric-kotlin"]
included = ["discord-ipc", "reflections"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
loom = { id = "fabric-loom", version.ref = "loom" }
